AccSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from accsyst.views import MyRegistrationView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='accsyst/')),
    url(r'^accsyst/', include('accsyst.urls'), name='accsyst_index'),
    url(r'^accsyst/accounts/login', include('registration.backends.simple.urls')),
    url(r'^accsyst/accounts/logout', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accsyst/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'accsyst'

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='accsyst/index.html'), name='index'),
    url(r'^worker_list/$', views.WorkerListView.as_view(), name='worker_list'),
    url(r'^worker/(?P<worker_id>\d+)/$', views.WorkerView.as_view(), name='worker'),
    url(r'^worker_form/(?P<worker_id>\d+)/$', views.WorkerFormView.as_view(), name='update_worker'),
    url(r'^worker_form/$', views.WorkerFormView.as_view(), name='add_worker'),
    # url(r'^card/(?P<worker_id>\d+)/$', views.CardView.as_view(), name='card'),
    url(r'^card_form/(?P<worker_id>\d+)/$', views.CardFormView.as_view(), name='card_form'),
    url(r'^report_list/$', views.ReportListView.as_view(), name='report_list'),
    url(r'^report/(?P<report_id>\d+)/$', views.ReportView.as_view(), name='report'),
    url(r'^report_form/$', views.ReportFormView.as_view(), name='report_form'),
    # url(r'^card/$', views.CardView.as_view(), name='card'),
]

accsyst/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Bill(models.Model):
    salary = models.IntegerField(null=True)
    hours = models.IntegerField(null=True)


class Card(models.Model):
    date = models.DateField(default=timezone.now())
    working_hours = models.IntegerField(blank=True, null=True)
    extra_hours = models.IntegerField(default=0, blank=True, null=True)
    day_hours = 8

    rate = models.IntegerField(blank=True, null=True)
    extra_coeff = 1.5
    fix_salary = models.IntegerField(blank=True, null=True)

    PAYMENT_CHOICE = (
        ('Csh', 'Cash'),
        ('Crd', 'Card')
    )
    payment = models.CharField(max_length=4, choices=PAYMENT_CHOICE, null=True)

    def save(self, *args, **kwargs):
        if self.working_hours > self.day_hours:
            self.extra_hours = self.working_hours - self.day_hours
        super(Card, self).save(*args, **kwargs)


class UserInfo(models.Model):
    name = models.CharField(max_length=20, null=True)
    surname = models.CharField(max_length=20, null=True)
    age = models.IntegerField(null=True)
    address = models.CharField(max_length=100, null=True)
    picture = models.ImageField(upload_to='profile_images', blank=True, null=True)


class Report(models.Model):
    workers = models.ManyToManyField('Worker', blank=True)
    accountants = models.ManyToManyField('Accountant')
    bills = models.ForeignKey(Bill, blank=True, null=True)
    info = models.CharField(max_length=100, blank=True, null=True)
    comments = models.CharField(max_length=500, blank=True, null=True)
    datetime = models.DateTimeField(default=timezone.now())


class AdminReport(Report):
    admin = models.ManyToManyField('Admin')


#  User profiles


class UserProfile(models.Model):
    card = models.OneToOneField(Card, blank=True, null=True)
    user_info = models.OneToOneField(UserInfo)

    class Meta:
        abstract = True


class Worker(UserProfile):
    accountant_ptr = models.ForeignKey('Accountant', blank=True, null=True)


class Accountant(models.Model):
    user = models.OneToOneField(User)
    admin_ptr = models.ForeignKey('Admin', null=True)


class Admin(models.Model):
    user = models.OneToOneField(User)

accsyst/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget

from .models import *


class BillForm(forms.ModelForm):
    salary = forms.IntegerField(help_text='Set the salary.', required=True)
    hours = forms.IntegerField(help_text='Working hours.', required=False)

    class Meta:
        model = Bill
        fields = '__all__'


class CardForm(forms.ModelForm):
    date = forms.DateField(widget=SelectDateWidget, initial=timezone.now(), help_text='Set the date.')
    working_hours = forms.IntegerField(help_text='Set working hours.')
    rate = forms.IntegerField(help_text='Set the rate.', required=False)
    fix_salary = forms.IntegerField(help_text='Set fix salary.', required=False)
    payment = forms.ChoiceField(help_text='Set the payment.', choices=Card.PAYMENT_CHOICE)

    class Meta:
        model = Card
        exclude = ['extra_hours', 'day_hours', 'extra_coeff']

    def clean(self):
        cleaned_data = super(CardForm, self).clean()
        rate = cleaned_data.get('rate')
        fix_salary = cleaned_data.get('fix_salary')
        cleaned_data = super(CardForm, self).clean()
        working_hours = cleaned_data.get('working_hours')
        if working_hours < 0 or working_hours > 24:
            raise forms.ValidationError('Enter correct working hours')
        if rate and fix_salary:
            raise forms.ValidationError('Choose only one way')
        if not (rate or fix_salary):
            raise forms.ValidationError('Choose at least one way')


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        exclude = ['accountants']


class AdminReportForm(forms.ModelForm):
    class Meta:
        model = AdminReport
        exclude = ['accountants', 'admin']


class UserInfoForm(forms.ModelForm):
    name = forms.CharField(help_text='Enter name.')
    surname = forms.CharField(help_text='Enter surname.')
    age = forms.IntegerField(help_text='Enter age.')
    address = forms.CharField(help_text='Enter address.')
    picture = forms.ImageField(help_text='Enter picture (optionally).', required=False)

    class Meta:
        model = UserInfo
        fields = '__all__'

accsyst/views.py
import subprocess

import pandas as pd
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect, reverse
from django.utils import timezone
from django.views.generic import View, FormView, ListView
from registration.backends.simple.views import RegistrationView

from .forms import *
from .models import *


class MyRegistrationView(RegistrationView):

    def get_success_url(self, user=None):
        return reverse('accsyst:index')


class CardFormView(FormView):
    template_name = 'accsyst/card_form.html'
    form_class = CardForm
    model = Card

    def post(self, request, *args, **kwargs):
        context_dict = {'form': self.form_class, 'worker_id': kwargs['worker_id']}
        card_form = self.form_class(data=request.POST)
        if card_form.is_valid():
            card = card_form.save(commit=False)
            card.save()
            try:
                worker = Worker.objects.get(id=context_dict['worker_id'])
                worker.card = card
                worker.save()
            except Worker.DoesNotExist as dne:
                print(dne)
            return redirect(reverse('accsyst:worker', kwargs={'worker_id': context_dict['worker_id']}))
        context_dict['form'] = card_form
        return render(request, self.template_name, context=context_dict)


# class CardView(FormView):
#     template_name = 'accsyst/card.html'
#     model = UserProfile
#
#     def get(self, request, *args, **kwargs):
#         context_dict = {'worker_id': kwargs['worker_id']}
#         try:
#             user = User.objects.get(username=context_dict['worker_id'])
#         except User.DoesNotExist:
#             return redirect(reverse('accsyst:index'))
#         profile_user = self.model.objects.get_or_create(user=user)[0]
#         context_dict['profile'] = profile_user
#         return render(request, self.template_name, context=context_dict)
#
#     def post(self, request, *args, **kwargs):
#         return redirect(reverse('accsyst:register_profile'))


class WorkerListView(ListView):
    template_name = 'accsyst/worker_list.html'
    model = Worker


class WorkerView(View):
    template_name = 'accsyst/worker.html'
    model = Worker

    def get(self, request, *args, **kwargs):
        context_dict = {}
        worker_id = int(kwargs['worker_id'])
        worker = None
        if worker_id == -1:
            try:
                worker = self.model.objects.create()
            except self.model.DoesNotExist:
                return redirect(reverse('accsyst:index'))
            except ValueError:
                pass
            context_dict['worker'] = worker
        if worker_id:
            try:
                worker = self.model.objects.get(id=worker_id)
            except self.model.DoesNotExist:
                return redirect(reverse('accsyst:index'))
            except ValueError:
                pass
            context_dict['worker'] = worker
        return render(request, self.template_name, context=context_dict)
    

class WorkerFormView(FormView):
    template_name = 'accsyst/worker_form.html'
    form_class = UserInfoForm
    model = UserInfo

    def post(self, request, *args, **kwargs):
        context_dict = {'form': self.form_class}
        userinfo_form = self.form_class(data=request.POST)
        if userinfo_form.is_valid():
            user_info = userinfo_form.save(commit=False)
            user_info.save()
            try:
                context_dict['id'] = kwargs['id']
                worker = Worker.objects.get(id=context_dict['id'])
                worker.user_info = user_info
            except KeyError as ke:
                worker = Worker.objects.create(user_info=user_info)
                context_dict['id'] = worker.id
                print(ke)
            worker.save()
            return redirect(reverse('accsyst:worker', kwargs={'worker_id': context_dict['id']}))
        context_dict['form'] = userinfo_form
        return render(request, self.template_name, context=context_dict)


class ReportListView(ListView):
    template_name = 'accsyst/report_list.html'
    model = Report


class ReportView(View):
    template_name = 'accsyst/report.html'
    model = Report

    def get(self, request, *args, **kwargs):
        context_dict = {}
        report_id = int(kwargs['job_id'])
        report = None
        if report_id:
            try:
                report = self.model.objects.get(id=report_id)
            except self.model.DoesNotExist:
                pass
            except ValueError:
                pass
            context_dict['report'] = report
        return render(request, self.template_name, context=context_dict)


class ReportFormView(FormView):
    template_name = 'accsyst/report_form.html'
    form_class = ReportForm
    model = Report
    
    def post(self, request, *args, **kwargs):
        context_dict = {'form': self.form_class}
        report_form = self.form_class(data=request.POST)
        if report_form.is_valid():
            report = report_form.save(commit=False)
            report.save()
            return redirect(reverse('accsyst:report'))
        context_dict['form'] = report_form
        return render(request, self.template_name, context=context_dict)

accsyst/templates/accsyst/base_bootstrap_carousel.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>
        AccSystem
        {% block title_block %}
        {% endblock title_block %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.1/examples/carousel/carousel.css" rel="stylesheet">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css"
          integrity="sha384-v2Tw72dyUXeU3y4aM2Y0tBJQkGfplr39mxZqlTBDUZAb9BGoC40+rdFCG0m10lXk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/fontawesome.css"
      integrity="sha384-q3jl8XQu1OpdLgGFvNRnPdj5VIlCvgsDQTQB6owSOHWlAurxul7f+JpUOVdAiJ5P" crossorigin="anonymous">

  </head>
  <body>

    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'accsyst:index' %}">
            AccSystem
            {% block head_block %}
            {% endblock head_block %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accsyst:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accsyst:worker_list' %}">WorkerList</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accsyst:report_list' %}">Reports</a>
            </li>
          </ul>
            <ul class="nav navbar-nav navbar-expand-sm px-1">
        {%  if user.is_authenticated %}
            <li class="nav-item text-nowrap px-2">
              <a class="nav-link" href="{% url 'auth_logout' %}"><i style="font-size:1.3em" class="fa fa-sign-out-alt px-1"></i>Logout</a>
            </li>
        {% else%}
            <li class="nav-item text-nowrap px-2">
              <a class="nav-link" href="{% url 'auth_login' %}"><i style="font-size:1.3em" class="fa fa-sign-in-alt px-1"></i>Login</a>
            </li>
        {% endif %}
      </ul>
        </div>
      </nav>
    </header>

    <main role="main">

      {% block body_block %}

      {% endblock body_block %}

      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous">
    </script>


    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- My scripts -->
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

accsyst/templates/accsyst/base_not_index.html
{% extends 'accsyst/base_bootstrap_carousel.html' %}

{% load staticfiles %}

{% block body_block %}
    <br><br>
    <div class="container col-md-6">
        {% block not_index %}

        {% endblock not_index %}
    </div>
{% endblock body_block %}

accsyst/templates/accsyst/card.html
{% extends 'accsyst/base_not_index.html' %}

{% load staticfiles %}

{% block title_block %}
    {% block head_block %}
            - Card {{ worker.id }}
    {% endblock head_block %}
{% endblock title_block %}

{% block not_index %}
     <div class="panel-heading">
        <!-- Display search results in an ordered list -->
        <div class="panel-body">
        <div class="list-group">
            {% for field in card %}
                <div class="col-md-8" style="font-size: large;">
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                    <br>
                </div>
                <hr>
            {% endfor %}
        </div>
        </div>
    </div>
    <br><br>
{% endblock not_index %}

accsyst/templates/accsyst/card_form.html
{% extends 'accsyst/form_base.html' %}

{% load staticfiles %}

{% block title_block %}
    {% block head_block %}
            - Card {{ worker.id }}
    {% endblock head_block %}
{% endblock title_block %}

accsyst/templates/accsyst/form_base.html
{% extends 'accsyst/base_not_index.html' %}

{% load staticfiles %}

{% block not_index %}
     <div class="panel-heading">
        <div>
        <form action="" method="post">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="col-md-8 affix" style="font-size: large;">
                    {{ field.help_text }}
                    <br>
                    {{ field }}
                    <br>
                    {% if field.errors %}
                        <br>
                        <div class="alert alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
                <hr>
            {% endfor %}
            {% if form.errors %}
                <br>
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <br>
            <button class="btn btn-primary" type="submit" name="submit">Submit</button>
        </form>
    </div>
    </div>
    <br><br>
{% endblock not_index %}

accsyst/templates/accsyst/report.html
{% extends 'accsyst/base_not_index.html' %}

{% load staticfiles %}

{% block title_block %}
    {% block head_block %}
            - Report {{ report.id }}
    {% endblock head_block %}
{% endblock title_block %}

{% block not_index %}
     <div class="panel-heading">
        <!-- Display search results in an ordered list -->
        <div class="panel-body">
        <div class="list-group">
            {% for field in report %}
                <div class="col-md-8" style="font-size: large;">
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                    <br>
                </div>
                <hr>
            {% endfor %}
        </div>
        </div>
    </div>
    <br><br>
{% endblock not_index %}

accsyst/templates/accsyst/report_form.html
{% extends 'accsyst/form_base.html' %}

{% load staticfiles %}

{% block title_block %}
    {% block head_block %}
            - Report {{ report.id }}
    {% endblock head_block %}
{% endblock title_block %}

accsyst/templates/accsyst/report_list.html
{% extends 'accsyst/base_not_index.html' %}

{% load staticfiles %}

{% block title_block %}
    {% block head_block %}
            - Reports
    {% endblock head_block %}
{% endblock title_block %}

{% block not_index %}
     <div class="panel-heading">
        <!-- Display search results in an ordered list -->
        <div class="panel-body">
        <div class="list-group">
        {% for report in report_list %}
            <div class="list-group-item" style="font-size: x-large">
            <div class="row">
                <a class="col-md-5" href="{% url 'accsyst:report' report.id %}">Report {{ report.id }}</a>
                <div class="col-md-7 row">
                    <div class="col-md-2">
                        {{ report.datetime }}
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}
        </div>
        </div>
    </div>
    <br><br>
{% endblock not_index %}

accsyst/templates/accsyst/worker.html
{% extends 'accsyst/base_not_index.html' %}

{% load staticfiles %}

{% block title_block %}
    {% block head_block %}
            - Worker {{ worker.id }}
    {% endblock head_block %}
{% endblock title_block %}

{% block not_index %}
     <div class="panel-heading">
        <!-- Display search results in an ordered list -->
        <div class="panel-body">
        <div class="list-group">
        <div class="form-group">
        <h2>{{ worker.user_info.name }} {{ worker.user_info.surname }}</h2>
        <div class="row">
            <div class="col-md">
                <p><h5>
                    Age: {{ worker.user_info.age }}
                </h5>
                <p><h5>
                    Address: {{ worker.user_info.address }}
                </h5>
                <p><h5>
                    {% if worker.user_info.picture %}
                        <img src="{{ MEDIA_URL }}{{ worker.user_info.picture.url }}"
                             width="300" height="300"/>
                    {% endif %}
                </h5>
            </div>
            <div class="col-md">
                {% if worker.card %}
                    <p><h5>
                        Date: {{ worker.card.date }}
                    </h5>
                    <p><h5>
                        Working hours: {{ worker.card.working_hours }}
                    </h5>
                    <p><h5>
                        {% if worker.card.extra_hours > 0 %}
                            Extra hours: {{ worker.card.extra_hours }}
                        {% endif %}
                    </h5>
                    <p><h5>
                        Rate: {{ worker.card.rate }}
                    </h5>
                    <p><h5>
                        Fix Salary: {{ worker.card.fix_salary }}
                    </h5>
                    <p><h5>
                        Payment: {{ worker.card.get_payment_display }}
                    </h5>
                {% endif %}
            </div>
        </div>
        </div>
        </div>
        <br>
        <a class="btn btn-primary" href="{% url 'accsyst:update_worker' worker.id %}">Update worker</a>
        <a class="btn btn-primary" href="{% url 'accsyst:card_form' worker.id %}">Update card</a>
    </div>
    <br><br>
{% endblock not_index %}

accsyst/templates/accsyst/worker_form.html
{% extends 'accsyst/form_base.html' %}

{% load staticfiles %}

{% block title_block %}
    {% block head_block %}
            - User Info
    {% endblock head_block %}
{% endblock title_block %}

accsyst/templates/accsyst/worker_list.html
{% extends 'accsyst/base_not_index.html' %}

{% load staticfiles %}

{% block title_block %}
    {% block head_block %}
            - Workers
    {% endblock head_block %}
{% endblock title_block %}

{% block not_index %}
     <div class="panel-heading">
        <!-- Display search results in an ordered list -->
     <a class="btn btn-primary" href="{% url 'accsyst:add_worker' %}">Add worker</a>
     <br><br>
        <div class="panel-body list-group">

            <div class="bg-dark" style="font-size: x-large; color: white" id="header">
                <div class="row px-3">
                    <div class=" col-md-5" id="name">
                        Worker name
                    </div>
                    <div class="col-md-7 row">
                        <div class="text-center col-md-5" id="id">
                            Worker id
                        </div>
                        <div class="text-center col-md-7">
                            <input id="select_all" type="checkbox" onclick="select_all()">
                        </div>
                    </div>
                </div>
            </div>
            </div>
        <form id="select_form">
        {% for worker in worker_list %}
            <div class="list-group-item" style="font-size: x-large">
            <div class="row">
                <a class="col-md-5" href="{% url 'accsyst:worker' worker.id %}">
                    {{ worker.user_info.name }} {{ worker.user_info.surname }}
                </a>
                <div class="col-md-7 row">
                    <div class="text-center col-md-5">
                        {{ worker.id }}
                    </div>
                    <div class="text-center col-md-7">
                        <input class="chbox" type="checkbox" onclick="select_worker()" value="{{ worker.id }}">
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}
        </form>
        </div>
        </div>
    </div>
    <br><br>
{% endblock not_index %}

{% block scripts %}
    <script src="{% static 'js/selection.js' %}?rand=12345"></script>
{% endblock scripts %}